### PR TITLE
Add Stencil for Swift Language

### PR DESCRIPTION
**Pull request by vknabel**
Within this PR I just added a new dialect.

It is especially useful for Sourcery.

The source code behind the example screenshot has been taken from [krzysztofzablocki/Sourcery](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/LinuxMain.stencil)

### CODE REVIEW

**Comment by svanimpe** [comment]
Hi @vknabel.

Thanks for the PR! We should definitely add this.

One quick question: how thoroughly have you tested the indentation rules? IIRC, those were the trickiest regular expressions to get right...

**Comment by vknabel** [comment]
Yes you're right, the indentation rules are tricky.
I did some further testing and needed to fix some smaller issues.

It has some problems if there are decreases are on one single line while the corresponding increases are distributed across multiple lines. Though I think this is a general issue of these regexes, right?

```swift
// correct: 2 inc, 2 dec
[{% for type in types.classes|based:"XCTestCase" %}
  {{ type }},
{% endfor %}]

// correct: 1 inc, 1 inc, 1. dec, 1 dec
[
  {% for type in types.classes|based:"XCTestCase" %}
    {{ type }},
  {% endfor %}
]

// wrong: 1 inc, 1 inc, 2 dec
[
  {% for type in types.classes|based:"XCTestCase" %}
    {{ type }},
  {% endfor %}]

```

Some further examples to show you some edge cases (which seem right to me):

```swift
switch (x) {
  {% for item in allItems %}
  case x:
    break
  {% endfor %}
default:
  break
}
``

**Comment by vknabel** [comment]
@svanimpe is this indentation-issue okay? Do have suggestions?

**Comment by svanimpe** [comment]
@vknabel Thanks, but please ask the regular Stencil contributers to review and merge this :)

I've donated this work to the Stencil project because I only had time to do the initial work, but not to keep it up to date. I'm no longer up-to-date on the Stencil codebase, nor do I have this grammar in my active memory :)

**Comment by vknabel** [comment]
Thanks for your response and initial work! Didn't know that you aren't involved into this project anymore, but I totally understand you.

Not sure who currently maintains Stencil itself, can someone of @ilyapuchka and @djbe help?

**Edit:** who can update this extension?

**Comment by Cyberbeni** [comment]
@vknabel I installed your version and the problem I had with the current version from the marketplace still exists, the pipe symbol completely breaks formatting:
```{% for type in types.all|annotated:"init" %}
// sourcery:inline:auto:{{ type.name }}.init
public init({% for variable in type.storedVariables %}{{variable.name}}: {{variable.typeName}}{% ifnot forloop.last %}, {% endif %}{% endfor %}) {
{% for variable in type.storedVariables %}
    self.{{variable.name}} = {{variable.name}}
{% endfor %}
}
// sourcery:end
{% endfor %}

{% for type in types.all where type|annotated:"isEqual" %}
// sourcery:inline:auto:{{ type.name }}.isEqual
override public func isEqual(to object: Any?) -> Bool {
    guard let other = object as? {{type.localName}} else { return false }
    return {% for variable in type.storedVariables %}{{variable.name}} == other.{{variable.name}}{% ifnot forloop.last %} &&
        {% endif %}{% endfor %}
}
override public var hash: Int {
    var hasher = Hasher()
{% for variable in type.storedVariables %}
    hasher.combine({{variable.name}})
{% endfor %}
    return hasher.finalize()
}
// sourcery:end
{% endfor %}
```
Looks like this:
Screenshot 2020-12-22 at 0 08 42

**Comment by vknabel** [comment]
@Cyberbeni I try to have a look on it this year. If the same highlighting glitch appears on the marketplace version and in the one of this PR, you probably should create a new issue in this repository for it. Feel free to @ me 👍

**Comment by vknabel** [comment]
Will probably never be merged - and I want to close stale prs.

**Pull request closed without merging**
